/* This is auto-generated code from LDmicro. Do not edit this file! Go
   back to the ladder diagram source for changes in the logic, and make
   any C additions either in ladder.h or in additional .c files linked
   against this one. */

/* You must provide ladder.h; there you must provide:
      * a typedef for SWORD and BOOL, signed 16 bit and boolean types
        (probably typedef signed short SWORD; typedef unsigned char BOOL;)

   You must also provide implementations of all the I/O read/write
   either as inlines in the header file or in another source file. (The
   I/O functions are all declared extern.)

   See the generated source code (below) for function names. */
#include "ladder.h"

/* Define EXTERN_EVERYTHING in ladder.h if you want all symbols extern.
   This could be useful to implement `magic variables,' so that for
   example when you write to the ladder variable duty_cycle, your PLC
   runtime can look at the C variable U_duty_cycle and use that to set
   the PWM duty cycle on the micro. That way you can add support for
   peripherals that LDmicro doesn't know about. */
#ifdef EXTERN_EVERYTHING
#define STATIC 
#else
#define STATIC static
#endif

/* Define NO_PROTOTYPES if you don't want LDmicro to provide prototypes for
   all the I/O functions (Read_U_xxx, Write_U_xxx) that you must provide.
   If you define this then you must provide your own prototypes for these
   functions in ladder.h, or provide definitions (e.g. as inlines or macros)
   for them in ladder.h. */
#ifdef NO_PROTOTYPES
#define PROTO(x)
#else
#define PROTO(x) x
#endif

/* U_xxx symbols correspond to user-defined names. There is such a symbol
   for every internal relay, variable, timer, and so on in the ladder
   program. I_xxx symbols are internally generated. */
STATIC BOOL I_b_mcr = 0;
#define Read_I_b_mcr() I_b_mcr
#define Write_I_b_mcr(x) I_b_mcr = x
STATIC BOOL I_b_rung_top = 0;
#define Read_I_b_rung_top() I_b_rung_top
#define Write_I_b_rung_top(x) I_b_rung_top = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XIN1(void);)

STATIC SWORD U_i_CCTD = 0;

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XIN2(void);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XIN3(void);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XIN4(void);)


/* You provide this function. */
PROTO(extern BOOL Read_U_b_XIN5(void);)

STATIC SWORD I_i_scratch2 = 0;
STATIC SWORD U_i_RLY1 = 0;
STATIC SWORD U_i_RLY2 = 0;
STATIC SWORD U_i_RLY3 = 0;
STATIC SWORD U_i_RLY4 = 0;
STATIC SWORD U_i_RLY5 = 0;
STATIC SWORD U_i_RLY6 = 0;
STATIC BOOL U_b_RRstTIMER = 0;
#define Read_U_b_RRstTIMER() U_b_RRstTIMER
#define Write_U_b_RRstTIMER(x) U_b_RRstTIMER = x
STATIC SWORD U_i_TTIMER1 = 0;
STATIC BOOL I_b_oneShot_0000 = 0;
#define Read_I_b_oneShot_0000() I_b_oneShot_0000
#define Write_I_b_oneShot_0000(x) I_b_oneShot_0000 = x
STATIC SWORD U_i_CCTD1 = 0;
STATIC BOOL U_b_RCTDATV = 0;
#define Read_U_b_RCTDATV() U_b_RCTDATV
#define Write_U_b_RCTDATV(x) U_b_RCTDATV = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YSAIDA2(void);)
PROTO(void Write_U_b_YSAIDA2(BOOL v);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YSAIDA3(void);)
PROTO(void Write_U_b_YSAIDA3(BOOL v);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YSAIDA4(void);)
PROTO(void Write_U_b_YSAIDA4(BOOL v);)

STATIC BOOL I_b_parOut_0000 = 0;
#define Read_I_b_parOut_0000() I_b_parOut_0000
#define Write_I_b_parOut_0000(x) I_b_parOut_0000 = x
STATIC BOOL I_b_parThis_0000 = 0;
#define Read_I_b_parThis_0000() I_b_parThis_0000
#define Write_I_b_parThis_0000(x) I_b_parThis_0000 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YSAIDA1(void);)
PROTO(void Write_U_b_YSAIDA1(BOOL v);)


/* You provide these functions. */
PROTO(BOOL Read_U_b_YSAIDA5(void);)
PROTO(void Write_U_b_YSAIDA5(BOOL v);)

STATIC BOOL I_b_parOut_0001 = 0;
#define Read_I_b_parOut_0001() I_b_parOut_0001
#define Write_I_b_parOut_0001(x) I_b_parOut_0001 = x
STATIC BOOL I_b_parThis_0001 = 0;
#define Read_I_b_parThis_0001() I_b_parThis_0001
#define Write_I_b_parThis_0001(x) I_b_parThis_0001 = x
STATIC BOOL I_b_parOut_0002 = 0;
#define Read_I_b_parOut_0002() I_b_parOut_0002
#define Write_I_b_parOut_0002(x) I_b_parOut_0002 = x
STATIC BOOL I_b_parThis_0002 = 0;
#define Read_I_b_parThis_0002() I_b_parThis_0002
#define Write_I_b_parThis_0002(x) I_b_parThis_0002 = x
STATIC BOOL I_b_parOut_0003 = 0;
#define Read_I_b_parOut_0003() I_b_parOut_0003
#define Write_I_b_parOut_0003(x) I_b_parOut_0003 = x
STATIC BOOL I_b_parThis_0003 = 0;
#define Read_I_b_parThis_0003() I_b_parThis_0003
#define Write_I_b_parThis_0003(x) I_b_parThis_0003 = x
STATIC BOOL I_b_parOut_0004 = 0;
#define Read_I_b_parOut_0004() I_b_parOut_0004
#define Write_I_b_parOut_0004(x) I_b_parOut_0004 = x
STATIC BOOL I_b_parThis_0004 = 0;
#define Read_I_b_parThis_0004() I_b_parThis_0004
#define Write_I_b_parThis_0004(x) I_b_parThis_0004 = x
STATIC BOOL I_b_parOut_0005 = 0;
#define Read_I_b_parOut_0005() I_b_parOut_0005
#define Write_I_b_parOut_0005(x) I_b_parOut_0005 = x
STATIC BOOL I_b_parThis_0005 = 0;
#define Read_I_b_parThis_0005() I_b_parThis_0005
#define Write_I_b_parThis_0005(x) I_b_parThis_0005 = x


/* Call this function once per PLC cycle. You are responsible for calling
   it at the interval that you specified in the MCU configuration when you
   generated this code. */
void PlcCycle(void)
{
    Write_I_b_mcr(1);
    
    /* start rung 1 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XIN1()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        U_i_CCTD = 1;
    }
    
    /* ] finish series */
    
    /* start rung 2 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XIN2()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        U_i_CCTD = 2;
    }
    
    /* ] finish series */
    
    /* start rung 3 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XIN3()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        U_i_CCTD = 3;
    }
    
    /* ] finish series */
    
    /* start rung 4 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XIN4()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        U_i_CCTD = 4;
    }
    
    /* ] finish series */
    
    /* start rung 5 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_XIN5()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        U_i_CCTD = 5;
    }
    
    /* ] finish series */
    
    /* start rung 6 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 0;
        U_i_RLY1 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 7 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 1;
        U_i_RLY2 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 8 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 2;
        U_i_RLY3 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 9 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 3;
        U_i_RLY4 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 10 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 4;
        U_i_RLY5 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 11 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_I_b_rung_top()) {
        I_i_scratch2 = 5;
        U_i_RLY6 = U_i_CCTD * I_i_scratch2;
    }
    
    /* ] finish series */
    
    /* start rung 12 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(Read_U_b_RRstTIMER()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(U_i_TTIMER1 < 9) {
            U_i_TTIMER1++;
            Write_I_b_rung_top(0);
        }
    } else {
        U_i_TTIMER1 = 0;
    }
    
    Write_U_b_RRstTIMER(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 13 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RRstTIMER()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(!Read_I_b_oneShot_0000()) {
            U_i_CCTD1++;
        }
    }
    Write_I_b_oneShot_0000(Read_I_b_rung_top());
    if(U_i_CCTD1 < 0) {
        Write_I_b_rung_top(0);
    } else {
        Write_I_b_rung_top(1);
    }
    
    Write_U_b_RCTDATV(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 14 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(U_i_CCTD1 > U_i_RLY1) {
    } else {
        Write_I_b_rung_top(0);
    }
    
    if(U_i_CCTD1 > U_i_RLY2) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA2()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA3()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA4()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0000(0);
    Write_I_b_parThis_0000(Read_I_b_rung_top());
    if(Read_I_b_parThis_0000()) {
        Write_U_b_YSAIDA1(1);
    }
    
    if(Read_I_b_parThis_0000()) {
        Write_I_b_parOut_0000(1);
    }
    Write_I_b_parThis_0000(Read_I_b_rung_top());
    if(Read_I_b_parThis_0000()) {
        Write_U_b_YSAIDA5(0);
    }
    
    if(Read_I_b_parThis_0000()) {
        Write_I_b_parOut_0000(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0000());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 15 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(U_i_CCTD1 > U_i_RLY2) {
    } else {
        Write_I_b_rung_top(0);
    }
    
    if(U_i_CCTD1 > U_i_RLY3) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA3()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA4()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA5()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0001(0);
    Write_I_b_parThis_0001(Read_I_b_rung_top());
    if(Read_I_b_parThis_0001()) {
        Write_U_b_YSAIDA2(1);
    }
    
    if(Read_I_b_parThis_0001()) {
        Write_I_b_parOut_0001(1);
    }
    Write_I_b_parThis_0001(Read_I_b_rung_top());
    if(Read_I_b_parThis_0001()) {
        Write_U_b_YSAIDA1(0);
    }
    
    if(Read_I_b_parThis_0001()) {
        Write_I_b_parOut_0001(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0001());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 16 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(U_i_CCTD1 > U_i_RLY3) {
    } else {
        Write_I_b_rung_top(0);
    }
    
    if(U_i_CCTD1 > U_i_RLY4) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA4()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA5()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA1()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0002(0);
    Write_I_b_parThis_0002(Read_I_b_rung_top());
    if(Read_I_b_parThis_0002()) {
        Write_U_b_YSAIDA3(1);
    }
    
    if(Read_I_b_parThis_0002()) {
        Write_I_b_parOut_0002(1);
    }
    Write_I_b_parThis_0002(Read_I_b_rung_top());
    if(Read_I_b_parThis_0002()) {
        Write_U_b_YSAIDA2(0);
    }
    
    if(Read_I_b_parThis_0002()) {
        Write_I_b_parOut_0002(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0002());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 17 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(U_i_CCTD1 > U_i_RLY4) {
    } else {
        Write_I_b_rung_top(0);
    }
    
    if(U_i_CCTD1 > U_i_RLY5) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA5()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA1()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA2()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0003(0);
    Write_I_b_parThis_0003(Read_I_b_rung_top());
    if(Read_I_b_parThis_0003()) {
        Write_U_b_YSAIDA4(1);
    }
    
    if(Read_I_b_parThis_0003()) {
        Write_I_b_parOut_0003(1);
    }
    Write_I_b_parThis_0003(Read_I_b_rung_top());
    if(Read_I_b_parThis_0003()) {
        Write_U_b_YSAIDA3(0);
    }
    
    if(Read_I_b_parThis_0003()) {
        Write_I_b_parOut_0003(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0003());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 18 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(U_i_CCTD1 > U_i_RLY5) {
    } else {
        Write_I_b_rung_top(0);
    }
    
    if(U_i_CCTD1 > U_i_RLY6) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA1()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA2()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_YSAIDA3()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0004(0);
    Write_I_b_parThis_0004(Read_I_b_rung_top());
    if(Read_I_b_parThis_0004()) {
        Write_U_b_YSAIDA5(1);
    }
    
    if(Read_I_b_parThis_0004()) {
        Write_I_b_parOut_0004(1);
    }
    Write_I_b_parThis_0004(Read_I_b_rung_top());
    if(Read_I_b_parThis_0004()) {
        Write_U_b_YSAIDA4(0);
    }
    
    if(Read_I_b_parThis_0004()) {
        Write_I_b_parOut_0004(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0004());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 19 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    /* start parallel [ */
    Write_I_b_parOut_0005(0);
    Write_I_b_parThis_0005(Read_I_b_rung_top());
    if(U_i_CCTD1 > U_i_RLY6) {
    } else {
        Write_I_b_parThis_0005(0);
    }
    
    if(Read_I_b_parThis_0005()) {
        Write_I_b_parOut_0005(1);
    }
    Write_I_b_parThis_0005(Read_I_b_rung_top());
    if(U_i_CCTD1 == U_i_RLY6) {
    } else {
        Write_I_b_parThis_0005(0);
    }
    
    if(Read_I_b_parThis_0005()) {
        Write_I_b_parOut_0005(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0005());
    /* ] finish parallel */
    if(Read_I_b_rung_top()) {
        U_i_CCTD1 = 0;
    }
    
    /* ] finish series */
}
